---
format:
  pdf:
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{caption}
        \captionsetup[figure]{labelformat=empty}
        \captionsetup[table]{labelformat=empty}
        \usepackage{lineno}
---

```{r ,echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE, fig.height=8,fig.width=8}


#Read now the downloaded occurrence data
#https://doi.org/10.15468/dl.saf8be
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(tidygeocoder)
library(pracma)
library(giscoR)
library(sf)
library(googlesheets4)
library(readr)
library(patchwork)
library(giscoR) #map of europe
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(patchwork)
library(rnaturalearth)

#Create tibble with the three cities
cities = tibble(Cities = c("Jena", "Halle", "Leipzig"))
#First find approximate coordinates for Jena, Halle and Leipzig
coords = cities %>%  geocode(Cities, method = 'osm', lat = Latitude , long = Longitude)

# Get all countries and transform to the same CRS
cntries <- gisco_get_countries(year = 2020,
                               resolution = 20) %>%
           st_transform(4326)


#Europe----
#Load europe map
Europe <- gisco_get_countries(region = "Europe")
europe_map = Europe %>% 
filter(CNTR_ID == "DE")

#Plot Europe map with counties of interest highlighted
p1 = ggplot(Europe) +
geom_sf(fill="gray25",color = "black", alpha = 0.5,size=0.2)  +
geom_sf(data= europe_map,
aes(fill = CNTR_ID, group=CNTR_ID),fill = "#f2ea69", color = "black",alpha=0.8, size = 0.25) +
coord_sf(xlim = c(-10, 30), ylim = c(35, 65))  + 
microplot::theme_collapse(panel.border = element_rect(colour = "black", fill=NA, size=2),
panel.background = element_rect(fill = "white")) +
geom_point(data = coords, aes(Longitude, Latitude, color= Cities), size = 0.15) +
scale_colour_manual(values=c("#440154FF", "#7AD151FF", "#2A788EFF")) +
theme(legend.position = "none")


#Modify coords for plotting
coords1 = tibble(Cities = c("Jena", "Halle", "Leipzig"), 
       Latitude = c(50.9,51.5,51.35),
       Longitude =c(11.4,11.8,12.1))

p2 = ggplot(europe_map) +
geom_sf(fill="gray25",color = "black", alpha = 0.5,size=0.2)  + 
microplot::theme_collapse(panel.border = element_rect(colour = "black", fill=NA, size=2),
panel.background = element_rect(fill = "white")) +
geom_point(data = coords, aes(Longitude, Latitude, color= Cities), size = 2) +
scale_colour_manual(values=c("#440154FF", "#7AD151FF", "#2A788EFF")) +
geom_text(data = coords1, aes(Longitude, Latitude, label = Cities), color= "black", hjust = -0.5) +
theme(legend.position = "none")



#Insert general plot within specific plot
panel1 = p2 + inset_element(p1, left = 0, bottom = -0.89 , right = 0.35, top = 1.23, ignore_tag = TRUE) 



#Try to prepare complementary informative graphs
#Load data
data = readRDS("../../Data/Working_files/interaction_data.rds")
plant_list = read_csv("../../Data/PollObs_species.csv")
#Generacte vector with species names
spp_list = plant_list %>%  
select(Accepted_name) %>% 
pull()

#Extract focal species that are not matching
spp_to_exclude = data %>% 
filter(Sampling == "Focal") %>% 
filter(!Plant %in% spp_list) %>% 
select(Plant) %>% 
pull()

#Exclude non-matching focals now
data = data %>% 
filter(!Plant %in% spp_to_exclude)
#Filter out species with 0 pollinators
data = data %>% 
filter(!Pollinator == "None")

#Explore interactions across time
#1st create date col
data = data %>%
mutate(Date = make_date(Year, Month, Day))
#Now summarise interactions by dates and bot garden
data_dates_1 = data %>% 
select(Interactions, Botanical_garden, Date) %>% 
group_by(Botanical_garden, Date) %>% 
summarise(Interactions = n())

#Prepare dataset with sampling method
data_dates_2 = data %>% 
select(Interactions, Botanical_garden, Date, Sampling) %>% 
group_by(Botanical_garden, Date, Sampling) %>% 
summarise(Interactions = n())

#Order levels
data_dates_2$Botanical_garden = factor(data_dates_2$Botanical_garden, 
                                       levels = c("Halle", "Leipzig", "Jena"))

data_dates_2_a = data_dates_2 %>%  filter(Sampling == "Focal")
data_dates_2_b = data_dates_2 %>%  filter(Sampling == "Random_census")

p2 = ggplot(data_dates_2_a) + 
  geom_line(aes(Date, Interactions, 
                colour = Botanical_garden, 
                linetype = "Dashed"), 
            stat = "identity") +
geom_line(data = data_dates_2_b, aes(Date, Interactions, 
      colour = Botanical_garden, 
      linetype = "Solid"),  stat = "identity") +
scale_colour_manual(
  values=c("#440154FF", "#2A788EFF", "#7AD151FF"),
  guide = "none") +
  scale_linetype_manual(
    values = c("Dashed" = "solid", "Solid" = "dashed"),
    labels = c("Focal obs.", "Random census"),
    name = "Sampling",
    guide = guide_legend(override.aes = list(colour = "black"))) +
facet_grid(Botanical_garden ~ .) +
theme_classic() +
theme(
  strip.background = element_blank(),
  strip.text = element_blank()) +
ylab(NULL) +
scale_y_continuous(name = NULL, sec.axis = sec_axis(~., name = "Interactions")) +
  guides(y = "none") +
theme(legend.position = "bottom", plot.title  = element_text(hjust=0.55, face = "bold")) +
ggtitle("Sampling period")



#Plot everything
panel2 = plot_spacer() / p2 / plot_spacer()+
plot_layout(widths = c(0.08, 0.18, 0.08), heights = c(0.1, 0.2, 0.)) 

panel1 + panel2 

```


```{r ,echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE, fig.height=8,fig.width=8,out.width="40%"}

#Read now the downloaded occurrence data
#https://doi.org/10.15468/dl.saf8be
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(tidygeocoder)
library(pracma)
library(giscoR)
library(sf)
library(googlesheets4)
library(readr)
library(patchwork)
library(giscoR) #map of europe
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(patchwork)
library(rnaturalearth)

#Create tibble with the three cities
cities = tibble(Cities = c("Jena", "Halle", "Leipzig"))
#First find approximate coordinates for Jena, Halle and Leipzig
coords = cities %>%  geocode(Cities, method = 'osm', lat = Latitude , long = Longitude)

# Get all countries and transform to the same CRS
cntries <- gisco_get_countries(year = 2020,
                               resolution = 20) %>%
           st_transform(4326)


#Europe----
#Load europe map
Europe <- gisco_get_countries(region = "Europe")
europe_map = Europe %>% 
filter(CNTR_ID == "DE")

#Plot Europe map with counties of interest highlighted
p1 = ggplot(Europe) +
geom_sf(fill="gray25",color = "black", alpha = 0.5,size=0.4)  +
geom_sf(data= europe_map,
aes(fill = CNTR_ID, group=CNTR_ID),fill = "#f2ea69", color = "black",alpha=0.8, size = 0.25) +
coord_sf(xlim = c(-10, 30), ylim = c(35, 65))  + 
microplot::theme_collapse(panel.border = element_rect(colour = "black", fill=NA, size=2),
panel.background = element_rect(fill = "white")) +
geom_point(data = coords, aes(Longitude, Latitude, color= Cities), size = 1.5) +
scale_colour_manual(values=c("#440154FF", "#7AD151FF", "#2A788EFF")) +
theme(legend.position = "none", panel.border = element_rect(colour = "black", fill=NA, size=4))


#Modify coords for plotting
coords1 = tibble(Cities = c("Jena", "Halle", "Leipzig"), 
       Latitude = c(50.9,51.7,51.35),
       Longitude =c(11.3,11.6,11.85))

p2 = ggplot(europe_map) +
geom_sf(fill="gray25",color = "black", alpha = 0.5,size=0.4)  + 
microplot::theme_collapse(panel.border = element_rect(colour = "black", fill=NA, size=4),
panel.background = element_rect(fill = "white")) +
geom_point(data = coords, aes(Longitude, Latitude, color= Cities), size = 7) +
scale_colour_manual(values=c("#440154FF", "#7AD151FF", "#2A788EFF")) +
#geom_text(data = coords1, aes(Longitude, Latitude, label = Cities), color= "black", hjust = -0.5, size=10) +
coord_sf(xlim = c(6.05, 14.9), ylim = c(47.55, 54.8))  + 
theme(legend.position = "none", panel.border = element_rect(colour = "black", fill=NA, size=4))


#Insert general plot within specific plot
panel1 = p2 + inset_element(p1, left = 0.005, bottom = -0.80 , right = 0.5, top = 1.25, ignore_tag = TRUE) 

panel1

```




```{r ,echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE, fig.height=8.5,fig.width=6.5,out.width="50%"}

#Read now the downloaded occurrence data
#https://doi.org/10.15468/dl.saf8be
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(tidygeocoder)
library(pracma)
library(giscoR)
library(sf)
library(googlesheets4)
library(readr)
library(patchwork)
library(giscoR) #map of europe
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(patchwork)
library(rnaturalearth)

#Try to prepare complementary informative graphs
#Load data
data = readRDS("../../Data/Working_files/interaction_data.rds")
plant_list = read_csv("../../Data/PollObs_species.csv")
#Generacte vector with species names
spp_list = plant_list %>%  
select(Accepted_name) %>% 
pull()

#Extract focal species that are not matching
spp_to_exclude = data %>% 
filter(Sampling == "Focal") %>% 
filter(!Plant %in% spp_list) %>% 
select(Plant) %>% 
pull()

#Exclude non-matching focals now
data = data %>% 
filter(!Plant %in% spp_to_exclude)
#Filter out species with 0 pollinators
data = data %>% 
filter(!Pollinator == "None")

#Explore interactions across time
#1st create date col
data = data %>%
mutate(Date = make_date(Year, Month, Day))
#Now summarise interactions by dates and bot garden
data_dates_1 = data %>% 
select(Interactions, Botanical_garden, Date) %>% 
group_by(Botanical_garden, Date) %>% 
summarise(Interactions = n())

#Prepare dataset with sampling method
data_dates_2 = data %>% 
select(Interactions, Botanical_garden, Date, Sampling) %>% 
group_by(Botanical_garden, Date, Sampling) %>% 
summarise(Interactions = n())

#Order levels
data_dates_2$Botanical_garden = factor(data_dates_2$Botanical_garden, 
                                       levels = c("Halle", "Leipzig", "Jena"))

data_dates_2_a = data_dates_2 %>%  filter(Sampling == "Focal")
data_dates_2_b = data_dates_2 %>%  filter(Sampling == "Random_census")


# Suponiendo que los datos están en data_dates_2_a y data_dates_2_b

# Suponiendo que los datos están en data_dates_2_a y data_dates_2_b
p2 = ggplot(data_dates_2_a) + 
  geom_line(aes(Date, Interactions, 
                colour = Botanical_garden, 
                linetype = "Dashed"), 
            stat = "identity", size = 2) +
  geom_line(data = data_dates_2_b, aes(Date, Interactions, 
      colour = Botanical_garden, 
      linetype = "Solid"),  stat = "identity", size = 2) +
  scale_colour_manual(
    values = c("#440154FF", "#2A788EFF", "#7AD151FF"),
    guide = "none") +
  scale_linetype_manual(
    values = c("Dashed" = "solid", "Solid" = "dashed"),
    labels = c("Focal obs.", "Random census"),
    name = "Sampling",
    guide = guide_legend(
      override.aes = list(colour = "black", size = 2.25)
    )) +
  scale_y_continuous(breaks = seq(0, max(data_dates_2_a$Interactions, data_dates_2_b$Interactions, na.rm = TRUE), by = 100)) +
  facet_grid(Botanical_garden ~ .) +
  theme(
    axis.line = element_line(color = "black"),
    axis.text = element_text(size = 20, color = "black"),
    axis.title = element_text(size = 22),
    axis.ticks = element_line(color = "black"),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 4),
    strip.background = element_blank(),
    strip.text = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(size = 18),
    legend.title = element_text(size = 20),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.55, face = "bold", size = 20),
    legend.key.size = unit(5, "line")
  ) +
  ylab(NULL)

p2

```
